### ISSUE TITLE
Issue using permanent hotspot

### ISSUE THREAD

**Issue by bmscmoreira** [RaspberryConnect/AutoHotspot-Installer#1]
Tried using option 4 (permanent hotspot). Feedback on the terminal was:

```
hostapd Config
Hostapd Status is  Y
Hostapd is installed
#RaspberryConnect.com - Autohotspot
Unmask and enable hostapd
hostapd.service disabled
Changing Hostapd Wifi country to  PT
Dnsmasq Config
#RaspberryConnect.com Autohotspot
Unmask & Enable Dnsmasq
dnsmasq.service disabled
hs-iptables.service enabled

The hotspot setup will be available after a reboot
The Hotspots WiFi SSID name is: RPiHotspot
The WiFi password is: 1234567890
Hotspot IP Address for ssh and VNC: 192.168.50.10
Press any key to continue
```

I then exited and rebooted, with my Pi4 still connected to the internet by an ethernet cable. But no raspberry pi hotspot network appeared. I then VNC'ed to the pi and clicking on the WIFI icon (top right) I get "no wireless interfaces found".

This is not a clean install of Raspbian 10. Any way I can help debug this?

**Comment by RaspberryConnect** [comment]
Hi, 
Thanks for the feedback. This looks like option 3, installing the permanent hotspot. Do you have custom config in /etc/dhcpcd.conf?  The changes to that file are appended to the file so any existing setup remains.

If you do have other setup in dhcpcd.conf what would be the issue if the file was backed up and replaced?

**Comment by bmscmoreira** [comment]
Yes, sorry, it was option 3.
I've executed the script - option 3 - with a blank dhcpcd.conf file and the network appeared, thanks!
