### ISSUE TITLE
Does not work with Raspberry Pi OS (Bookworm)

### ISSUE THREAD

**Issue by dwardu89** [RaspberryConnect/AutoHotspot-Installer#19]
I've tried installing this on Bookworm and it looks like we will need to remove networkmanager and replace it with dhcpcd if we were going to continue down this route.

**Comment by RaspberryConnect** [comment]
Hi,  
No it doesn't work in Bookworm a network manger is used instead of dhcpcd. There is a compatability note in the readme.

A bookworm version is in testing and will be released once finished.  Hopefully not too much longer, but i need to finished a diffent project first.
