### ISSUE TITLE
Not Working with the 64 bit version

### ISSUE THREAD

**Issue by CarriedArtist41** [RaspberryConnect/AutoHotspot-Installer#5]
When I try to run the installer says it just for the PiOS and Raspbian, but i am using the 64 bit version of PiOS

**Comment by RaspberryConnect** [comment]
It seems PiOS 64 shows as Debian and PiOS 32 is Raspbian. I have added Debian to the OS checks.
This script requires dhcpcd as the DHCP client. As this will allow the script to run on non official Pi Debian OS's that may not be using dhcpcd, there are now checks that dhcpcd is running as well.

Thanks for pointing this out.
