### ISSUE TITLE
Wrong DAEMON_CONF

### ISSUE THREAD

**Issue by bitworking** [RaspberryConnect/AutoHotspot-Installer#7]
Hey, thanks for this script. I tried it and it didn't work for me. I investigated and found that the DAEMON_CONF is wrong.

https://github.com/RaspberryConnect/AutoHotspot-Installer/blob/ddb4916cbf2ece87bcf19c754f68c648d8827edd/AutoHotspot-Setup/Autohotspot/config/hostapd#L13

It should be: `DAEMON_CONF="/etc/hostapd/hostapd.conf" `

After this change everything works like a charm!

**Comment by RaspberryConnect** [comment]
Thanks for pointing that out. I take it you are using Raspbian Stretch as that file is not used in Buster or Bullseye?
The script has not been tested on Stretch so that one got through. Updated now.

**Comment by bitworking** [comment]
Yes right, using version 9 scretch. Thanks, I will close that.
